FROM golang:1.21.6

WORKDIR /app

COPY ./go.mod ./
COPY ./go.sum ./

RUN go mod download

COPY ./cmd/okta-sync/*.go ./cmd/okta-sync/
COPY ./cmd/okta-sync/cmd/*.go ./cmd/okta-sync/cmd/
COPY ./scripts/sql/*.sql ./scripts/sql/
COPY ./internal ./internal

WORKDIR /app/cmd/okta-sync
RUN go build -o /okta-sync

ENTRYPOINT [ "/okta-sync" ]