# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com

# The lines below are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/need to use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy

builds:
  - id: gst
    main: ./cmd/gst
    env:
      - CGO_ENABLED=0
    binary: gst
    goos:
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - "-s -w -X github.com/reecewilliams7/go-security-tools/cmd/gst/cmd.version={{.Version}}"

  - id: gst-tui
    main: ./cmd/gst-tui
    env:
      - CGO_ENABLED=0
    binary: gst-tui
    goos:
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - "-s -w"

  - id: gst-web
    main: ./cmd/gst-web
    env:
      - CGO_ENABLED=0
    binary: gst-web
    goos:
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - "-s -w"

checksum:
  name_template: gst_{{.Version}}_checksums.txt

archives:
  - id: gst
    ids: [gst]
    formats: ["tar.gz"]
    name_template: >-
      gst_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        formats: ["zip"]

  - id: gst-tui
    ids: [gst-tui]
    formats: ["tar.gz"]
    name_template: >-
      gst-tui_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        formats: ["zip"]

  - id: gst-web
    ids: [gst-web]
    formats: ["tar.gz"]
    name_template: >-
      gst-web_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        formats: ["zip"]

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  draft: true
  footer: >-

    ---

    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).
