# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: On Tag

on:
  workflow_dispatch:
  push:
    tags: [ "*" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write    
    steps:
      - uses: actions/checkout@v3

      # - name: Set up Zip
      #   run: apt install zip -y

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Install dependencies
        run: go get -v ./...  

      - name: Test
        run: go test -v ./cmd/gst            

      - name: Build Windows AMD64
        run: env GOOS=windows GOARCH=amd64 go build -o build/gst-win-x64.exe -v ./cmd/gst

      - name: Linux AMD64
        run: env GOOS=linux GOARCH=amd64 go build -o build/gst-linux-x64 -v ./cmd/gst
        
      - name: Linux ARM64
        run: env GOOS=linux GOARCH=arm64 go build -o build/gst-linux-arm64 -v ./cmd/gst

      - name: Linux ARM
        run: env GOOS=linux GOARCH=arm go build -o build/gst-linux-arm -v ./cmd/gst   

      - uses: actions/upload-artifact@v4
        with:
          name: gst_windows_amd64
          path: build/gst-win-x64.exe

      - uses: actions/upload-artifact@v4
        with:
          name: gst_linux_amd64
          path: build/gst-linux-x64
          
      - uses: actions/upload-artifact@v4
        with:
          name: gst_linux_arm64
          path: build/gst-linux-arm64   
          
      - uses: actions/upload-artifact@v4
        with:
          name: gst_linux_arm
          path: build/gst-linux-arm
          
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "build/gst*"      